### ISSUE TITLE
Autoswap enable screen should show fee summary

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-btcpay-plugin#9]
We should show one or both pairs (depending if chain swaps were configured or not) fee summary here:
![image](https://github.com/user-attachments/assets/e949e435-ad0c-49ca-b421-989286ac7b27)

List UI shoud be like the one we use in Standalone:
![image](https://github.com/user-attachments/assets/4786c5e3-6b8a-43ce-be40-9c7418a0e6d6)

Adjusted Figma:
![image](https://github.com/user-attachments/assets/e6513cac-1f30-4129-9d93-a183626defa0)

**Comment by jackstar12** [comment]
Feel like this is too much info for enable step - fees were already shown in the previous steps and the focus should be on wether swaps will be recommended right now.
